### ISSUE TITLE
Explicit versions prevent fixing npm vulnerabilities

### ISSUE THREAD

**Issue by m3fawner** [webpro/dyson#110]
Lodash 4.17.20 has a reported vulnerability addressed in version 4.17.21, however, as a result of explicitly requiring 4.17.20 in Dyson, we can't effectively address the vulnerability.

Would you be against having all of the packages have the appropriate semantic modifiers?

**Comment by webpro** [comment]
Good idea, I've just published [v4](https://github.com/webpro/dyson/releases/tag/4.0.0) (major bump because of Node.js v10).

**Comment by m3fawner** [comment]
Thank you!
