### ISSUE TITLE
Use Dyson as mock api for tests purposes

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [webpro/dyson#28]
Hi, is there a way to run Dyson as mock api with mocha + supertest? Can I require("dyson") inside my tests code?
Because I have an api which consumes another apis and I'd like to build some mocks for theses apis using dyson for test purposes.

**Comment by webpro** [comment]
Yes, that sounds feasible, see [cli.js](https://github.com/webpro/dyson/blob/45ac8fe45a40273c250446cceff2289a2011a8ab/lib/cli.js#L29-L42). This is something minimal that might do what you need (provided dyson is installed as d(evD)ependency:

```js
var dyson = require('dyson');
dyson.bootstrap({
    port: 3000,
    configDir: 'path/to/templates'
});
```

**Comment by caio-ribeiro-pereira** [comment]
Thanks a lot! This code will be very useful for me!

**Comment by caio-ribeiro-pereira** [comment]
Hi again, I'm having problems to run dyson server with mocha, because my tests are running while dyson is up running the `dyson.bootstrap` is async, and sometimes my tests crash because the dyson is not ok yet.

Is there a way to start dyson in a sync way?

**Comment by webpro** [comment]
Not 100% sure, but I think dyson reads the template files synchronously. I don't think there's any async stuff going during bootstrap, but in any case there is no such thing as a bootstrap callback.

If you can show me your setup, I can take a look at it.

**Comment by caio-ribeiro-pereira** [comment]
Forget it, the `dyson.bootstrap` is a sync function. And the problems was in my code and not the bootstrap function.

**Comment by webpro** [comment]
OK glad you've found the issue.

**Comment by rrjoshi92** [comment]
Is there a way to stop the Dyson server after all the test?  currently, I am using it with mocha and my test never ends since the server is still running.
