### ISSUE TITLE
Post With Collections

### ISSUE THREAD

**Issue by morten-kirstein** [webpro/dyson#29]
Hi im trying to figure out how to use collections in POST, is it possible to have you write an example.

**Comment by webpro** [comment]
I noticed an issue in setting up the defaults (i.e. not setting a default for `size`). I've fixed that.

So either you need to set `size` (as a number of function), or update to the version I just released (0.3.5) and use `_.random(2, 10)` as the default for `size` without setting anything for that prop yourself.

Does that help?

**Comment by morten-kirstein** [comment]
Hey thx for the quick reply and bugfix.

It kinda worked but, the way i'm using the POST method is kinda wrong i think.

If i want different content out and be able to switch template depending what request query i supply how do i do that?

This is how i'm doing it right now:
---------------------------------------------------------------

var g = require('dyson-generators');
var faker = require('faker');

var products = {
    path: '/api/search',
    cache: false,
    collection: true,
    size: 5,
    template: {
        id: g.random(5),
        Producturl: faker.internet.domainName(),
        PicutureUrl: "",
        name: "xxxxxx",
        stock: {
            city: {
                name: g.address.city(),
                amount: g.random(20)  
            },
            central: g.random(40)
        }
    },
    container: {
        layout: 'group',
        product: function(params, query, data){
            return data;
        }
    }
};

module.exports = products;

**Comment by morten-kirstein** [comment]
Sorry that was my get. The post is here.
----------------------------------------------------------

var g = require('dyson-generators');
var faker = require('faker');

var domainName = 'http://www.xxx/';

var outputtemplate = {    
        ProductUrl: domainName + faker.helpers.randomNumber(555),
        ImageUrl: faker.image.imageUrl(30,30,'cats'),
        ProductName: faker.company.catchPhraseAdjective(),
        ProductSupplierNo: faker.helpers.randomNumber(9999999999)
    };

var products = {
    path: '/api/search',
    collection: true,
    size: 5,
    template: outputtemplate
};  


module.exports = products;

**Comment by webpro** [comment]
FYI, code is much better readable if you'd put it in [code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) (you can still edit).

I think your question might be answered by saying that most things (the template itself, or individual template properties) can be a function (https://github.com/webpro/dyson#endpoint-configuration), and these functions are invoked with the request parameters and query.
