### ISSUE TITLE
How can I force an server err?

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [webpro/dyson#30]
Hi again! I'm using a lot your module and now I having problems to mock a server status 500 error for my tests.

I built this mock: `GET /hello`

``` javascript
{
    path: "/hello",
    cache: false,
    collection: false,
    render: function(req, res) {
      res.status(500).json({});
    }
  }
``` 

But even the server returning status 500, I can't get the request error when I run this code...

``` javascript
var request = require("request");

app.get("/another-hello", function(req, res) {
   request.get("/hello", function(err, resp, body) {
      if (err) console.log(err); // I can't get this error....
     //...
   });
});
``` 

Do you know another way to mock an server error?

**Comment by webpro** [comment]
The error you are referring to is not the same as e.g. a `404` or `500` HTTP status code. From the perspective of the `request` module to make a request, there was no error (i.e. the response has arrived). It's just that the response (`resp`) happens to contain a `500` status code. You can check it with `resp.statusCode`, so your example would like this:

```
request.get('/hello', function(err, resp, body) {
    console.log(resp.statusCode);
});
```
This should print `500`.

**Comment by caio-ribeiro-pereira** [comment]
So are you tell me that dyson can't simulate an request error, only force status 500?
I wrote this workaround

``` javascript
{
    path: "/hello",
    cache: false,
    collection: false,
    render: function(req, res) {
      throw "Server error";
    }
}
```

But it doesn't make an error, only status 500.

**Comment by webpro** [comment]
Please take into account that an exception (e.g. `SyntaxError`, `ReferenceError`) _within your JavaScript application_ is something entirely different compared to HTTP status codes (e.g. `500`) _between servers_.

In other words: you should be handling exceptions within an application, but between servers (e.g. when doing a request as in the code above) you should be handling HTTP status codes. Or, from a different perspective, what if the mocking service (dyson) was written in another language (say, Java)?

**Comment by caio-ribeiro-pereira** [comment]
I didn't understand the exception example you give, could you write a code example?
