### ISSUE TITLE
support HTTP method as a property of endpoint?

### ISSUE THREAD

**Issue by ottocol** [webpro/dyson#33]
Hi, I would like to know if there is any way to specify HTTP method in the endpoint configuration instead of assigning a specific method to a folder, because I would like to group code by entity and not by method (e.g. "orders.js" implementing an "orders" service, with GET/POST/PUT,  clients.js being "clients" service, with same methods...)

Don't want to bother sending this as an issue so feel free to close this mercilessly if this is not the appropriate place to ask this question.

**Comment by webpro** [comment]
No worries, it's a fair question. The thing is, this project has been built up with the "methods" folder structure, so it might require quite a refactoring. I'm gonna give it a look soon anyway.

**Comment by webpro** [comment]
Hi @ottocol, as a result of the work in b75f8df08c18aa39f4bdeec39504640d0004ddc1 (related to #37) this should now work as well. Just released as v0.6.0. I would be glad to hear your findings if you have any.
