### ISSUE TITLE
Usage as connect middleware

### ISSUE THREAD

**Issue by dwightjack** [webpro/dyson#36]
Hi,

In my current scenario i'd like to use a connect app as static file server (via grunt-contrib-connect) and create a fake API endpoint at `/api`. 

I was wondering if it's possible to use dyson as a connect middleware. This way i won't have to use plugins like `grunt-concurrent` keeping the stack more lightweight.

**Comment by webpro** [comment]
That doesn't seem very easy to do atm.

Here is where middleware is registered with Express: https://github.com/webpro/dyson/blob/f2dabb21bb80aad2c61815b89a2622c7cc5c79a0/lib/dyson.js#L62. One option is to rewrite this `dyson.js` file/module to your own likings (and import the other modules from dyson).

Let me know if there's anything I can do to help out.

**Comment by dwightjack** [comment]
Thanx!

Reading the source I was thinking that passing a connect application
instance as option to the bootstrap methed cuold be an solution. Then if
Application option is passed in dyson would attach methods to that instance
instead of generating a new one.

It's less elegant, and not really a plain middleware but maybe it's the
easiest way.

In the next few days i'll fork the repo and check it out.

Thanx for the support!
Il 23/apr/2015 20:36, "Lars Kappert" <notifications@github.com> ha scritto:

**Comment by webpro** [comment]
Hey @dwightjack, any news on this? If you're still interested I could look into making dyson available as middleware (not sure how, yet).

**Comment by webpro** [comment]
@dwightjack, the changes that @rixo made recently, might help you out.

If we support to pass your own `app` instance to the bootstrap function, so `registerServices` uses that, I guess it does what you need. Let me know how it goes :-) I'm going to close this one for now. Feel free to open a PR or re-open this one to discuss further.

**Comment by dwightjack** [comment]
Hi,

thank you. I didn't had the chance to work properly on it. Anyway thanks for the update, as soon as I'll work again on the project involving dyson i'll let you know!
