### ISSUE TITLE
2 Deprecated warnings

### ISSUE THREAD

**Issue by matthiasfeist** [webpro/dyson#39]
Hi.

On startup there is a message
`static-icon deprecated; switch to module serve-favicon`

Also, if I run the example from the readme: `res.send(401, 'Forbidden');` I get a message that this is deprecated and `res.send(401).body('Forbidden');`should be used instead

**Comment by webpro** [comment]
Could you please submit a PR with the fixes?

**Comment by matthiasfeist** [comment]
Pull request created :)

**Comment by webpro** [comment]
Closing by #40.
