### ISSUE TITLE
GET cannot return non-object data

### ISSUE THREAD

**Issue by cody1024d** [webpro/dyson#42]
I was wondering if there was a way (or plans?) to allow the template to be raw data, as opposed to an object.

Because of poor server-side code, I need to support an endpoint that returns a raw boolean, not wrapped in a json object.  (Basically I want to specify that template: true).  Can Dyson do this?

**Comment by cody1024d** [comment]
Figured it out using the callback property.  Passing in a custom function, where the response body is populated with the data I need (in my case the boolean true)

**Comment by webpro** [comment]
Glad it works for you. I was hoping you could also a function for `template` to return `true`, but looking at the code it should return either an object or an array.

**Comment by cody1024d** [comment]
Yeah, tried that as well.  Passing in the custom function is a little less than desired, but works out perfectly well in the end either way!  Would you be interested in a PR at some point in the future to support passing in a function that returns true to template?

Mind you, I haven't looked at the code to see how feasible this is or anything, but it seems like a quality-of-code improvement.

**Comment by webpro** [comment]
You're welcome to submit a PR! I think it's [not too hard](https://github.com/webpro/dyson/blob/6c21b9b764b5bce84f1f6cbc3c7b9baacbd0b591/lib/response.js#L76-L83) to implement.
