### ISSUE TITLE
Allow proxying requests randomly

### ISSUE THREAD

**Issue by pjacekm** [webpro/dyson#48]
This request is based on the discussion that took place in Issue #45. 

I'd like to have the option in Dyson to create such configuration that would allow part of the requests to the same resource get proxied randomly, while some of them would generate mocked (locally defined) response. 

For example, let's say if the same resource URL GET /api/Clients/ is requested 3 times, it gets proxied to the remote API twice, and one time Dyson generates mocked response from the template or `callback: functionName`. I'd like to proxy most of the requests to the remote API, and generate ugly errors once in a while.

Possible reasons for such configuration could include: 
- When all calls to the remote API require authentication header (OAUTH), you can't generate the auth header locally and then proxy other requests to the remote API, it's either all proxied, or all local, 
- When the remote API is big and complex, generating API responses locally would be a big headache, due to its complexity and size. Being able to "inject" false errors occasionally would help in testing the code of the client application.

In my opinion, such setting should be available at the individual resource config level, and the probability number could be an integer, say between 1 and 10, just to avoid playing with decimals and make this setting more clear to the users. Perhaps simply by allowing the proxy value to be `true` (proxying all requests), `false` (proxying no requests, all responses generated locally) or a `number` that represents the likeliness the request will be proxied.

**Comment by rixo** [comment]
I've opened a new issue to suggest a more general feature that would also cover this use case.

@pjacekm I'm curious to why you want to introduce randomness, that is unpredictability, in the behaviour of the mock layer. For testing, that you want systematic and interpretable, you need the mocks to be predictable and deterministic. Are you using dyson in the context of some kind of stress test maybe?

Regarding this issue, I must disagree on the idea to use an arbitrary score system to express probability rather than a 0-1 ratio that is the universal standard in this respect.

**Comment by webpro** [comment]
Why not override the `render` function, you can do any kind of custom stuff in there:

```
module.exports = {
    path: '/path',
    render: function(req, res) {
        if(Math.random() > .5) {
            res.status(500).send('Random error');
        } else {
            res.set('Content-Type', 'application/json');
            res.send(200).send(res.body);
        }
    },
    template: {}
};
```

or

```
var request = require('request');

module.exports = {
    path: '/path',
    render: function(req, res) {
        if(Math.random() > .5) {
            res.status(500).send('Random error');
        } else {
            req.pipe(request('http://real.org/path')).pipe(res);
        }
    },
    template: {}
};
```

**Comment by pjacekm** [comment]
Thank you for your comments and suggestions. I was able to meet with our team, and we agreed on the fact that randomness would introduce unpredictability, which is not good. Closing the issue.
