### ISSUE TITLE
Allow delayed proxied responses

### ISSUE THREAD

**Issue by pjacekm** [webpro/dyson#49]
While you can delay a response in a resource config files:

```
setTimeout(function(){
    res.status(400).send({"error": "I am a delayed response"});
    next();
}, 10000);
```
...there's no simple way to delay a proxied response. It would be awesome to have such option in Dyson.
A delay could be treated as a random value with limits, for example:
```
module.exports = {
    path: '/api/clients',
    proxy: true, 
    proxyResponseDelay: [0,120] // Delay between 0 and 120 seconds
};
```

**Comment by webpro** [comment]
Thanks for feature request, wanted this myself for quite a while. I've added a `delay` configuration for endpoint templates, and a global `proxyDelay` option. It's released as v0.8.0, please let me know how it works for you :-)
