### ISSUE TITLE
Allow simulation of connection errors

### ISSUE THREAD

**Issue by pjacekm** [webpro/dyson#50]
While you can simulate server-side errors:
```
res.status(400).send({"error": "invalid_grant"});
```
```
res.status(500).send("Internal server error");
```
...you can't simulate "connection interrupted/dropped", "connection timeout", "slow network" and similar server/network failure scenarios. It would be an awesome addition to Dyson. Useful especially in situations where you are mocking or testing applications that are not executed in Web browsers (where some of these errors can be simulated using e.g. Chrome developer tools).

Maybe integrating with or implementing similar ideas as in [Toxy project](https://github.com/h2non/toxy)? ;)

**Comment by webpro** [comment]
You can override the `render` method and inject your "poison" there, right?

**Comment by m3fawner** [comment]
@webpro that is correct. That is how I've implemented my error cases.

**Comment by webpro** [comment]
I'm going to close this one. With https://github.com/webpro/dyson/commit/5f6d66253fb4afa645f68033f96cf71767848de4 I hope to support more custom use cases and middlewares (like this one). Feel free (re)open, though.
