### ISSUE TITLE
Add option to manage headers in proxied requests

### ISSUE THREAD

**Issue by pjacekm** [webpro/dyson#51]
(This is a follow-up of a discussion in #45)

In certain situation, proxied requests can fail with 404 (when a remote API is behind a reverse proxy) or 500 (when a connection to a remote API is made over HTTPS) errors. The crossing point of those errors is the `Host` header.

The Host header is added by the party making the request, and is mandatory according to HTTP specs. The problem is that currently Dyson is just indiscriminately sending all the original request headers (in which Host point to the dyson server) to the target endpoint. This causes two issues. On Dyson's side, node's https module chokes when it verifies the certificate identity because (I think) it relies on the Host header to determine who we think we are talking to. On the other end, the Host header is needed by the reverse proxy (e.g. nginx) to determine the actual target server. When the Host header contains a forwarded host name, the reverse proxy can't find the destination host based on the request Host header, and returns a 404 error. 

Current workaround includes replacing [this line](https://github.com/rixo/dyson/blob/dedi/lib/proxy.js#L26) by the following:

```
headers: require('lodash').omit(req.headers, ['host'])
```

...which is not an ideal solution.

The issue can be treated in 2 ways:
- Strip specific header(s) out the request (as in the example above),
- Let specific headers be overwritten by resource file configuration, for example:

```
module.exports = {
    path: '/api/clients',
    proxy: true, 
    proxyHeaders: {
        'host':'www.myHost.com',
        'X-My-Always-Added-Header':'value'
    }
};
```

**Comment by webpro** [comment]
Hi @pjacekm, I've just pushed a change to master including docs (https://github.com/webpro/dyson/commit/5f6d66253fb4afa645f68033f96cf71767848de4) that should allow to handle some use cases like yours more easily. Happy to hear your feedback/suggestion if it still matters to you.

**Comment by webpro** [comment]
Closing this old issue, feel free to re-open.
