### ISSUE TITLE
Document how to return JSONP response

### ISSUE THREAD

**Issue by mgryszko** [webpro/dyson#53]
I made a quick writeup about [Dyson and JSONP](https://gist.github.com/mgryszko/ec2820ae73f97711867d). I can extend the documentation with a section based on this example. Is it OK to you?

**Comment by webpro** [comment]
That would be great, @mgryszko. Please keep it nice and concise :-)

**Comment by mgryszko** [comment]
Pull request #59 solves this issue.

**Comment by webpro** [comment]
Closed by #59.
