### ISSUE TITLE
How to configure dyson responses to have root nodes?

### ISSUE THREAD

**Issue by jrhorn424** [webpro/dyson#56]
To get dyson to work with the default Ember RESTAdapter, I need dyson to return rooted JSON responses. I've read the docs but may have missed something... is there a way to respond with this:

```
# GET /users/8
{
  "user": {
    "id": 8,
    "first": "David",
    "last": "Tang",
    "pets": [ 1, 2, 3 ],
    "company": 7
  }
}

# GET /users
{
  "users": [
    {
      "id": 8,
      "first": "David",
      "last": "Tang",
      "pets": [ 1, 2, 3 ],
      "company": 7
    },
    {
      "id": 9,
      "first": "Jane",
      "last": "Doe",
      "pets": [ 4 ],
      "company": 7
    }
  ]
}
```

**instead** of this:

```
# GET /users/8
{ "id": 8, "first": "David", "last": "Tang" }

# GET /users
[
  { "id": 8, "first": "David", "last": "Tang" },
  { "id": 9, "first": "Jane", "last": "Doe" }
]
```

**Comment by webpro** [comment]
You can use the [container](https://github.com/webpro/dyson#containers) property. Let me know if this works for you.

**Comment by jrhorn424** [comment]
Great, that works! It didn't occur to me that "data" and "meta" and such were clues that you could use container for [json-api](http://jsonapi.org). I assumed these were special to dyson. Thanks!
