### ISSUE TITLE
Maximum of 25 end points per HTTP method?

### ISSUE THREAD

**Issue by m3fawner** [webpro/dyson#60]
I seem to have maxed the number of end points supported by dyson, though I don't see it anywhere in the documentation.

Is there a way to override this limit? I can rename the 26th file and make it come before another alphabetically, and then it works, but the newest 26th file is no longer available.

**Comment by webpro** [comment]
I had no idea. Are you sure it's dyson? Can you set up something so I can reproduce it?

**Comment by m3fawner** [comment]
To be honest, I can't tell if it's dyson or some other dependency. Whatever is occurring, there are no error messages that are being displayed. It simply doesn't start some of the end points. I, unfortunately, can't share my dyson set up, as it contains info I think my company would deem private.

**Comment by m3fawner** [comment]
I don't want to publicly admit how dumb I feel right now, but it's only fair for this mistake:

It turns out that I had a file that had improperly formatted JSON in the response template. Dyson would fail silently when reading that file and, depending on the order in which the files were read, would serve up those that were successful.

When I upgraded dyson versions, it no longer failed silently, and pointed out my mistake. Everything is great. Thank you for your product @webpro. It's been immensely beneficial to my development process.

**Comment by webpro** [comment]
No worries, I'm just glad you sorted it out, and in general that this tool is useful to you!
