### ISSUE TITLE
Dyson with Connect

### ISSUE THREAD

**Issue by nathagey** [webpro/dyson#68]
Do you have any recommendations to integrating a dyson server with [connect](https://github.com/senchalabs/connect)?

I'm hoping to combine these...

```
http.createServer(app).listen(port);
dyson.bootstrap({
	configDir: "services",
	port: 3000
});
```

**Comment by webpro** [comment]
Apologies for reacting so late, I've totally missed it.

However, I'm afraid it won't go well with connect.

(But it does go well with Express: see the second part of https://github.com/webpro/dyson#custom-middleware.)
