### ISSUE TITLE
Overriding 'status' no longer allows default behavior?

### ISSUE THREAD

**Issue by phobetron** [webpro/dyson#70]
At least in 0.10.0, overriding `status`, as in the example code and demos, no longer sends along the generated output from the template. I've tried a few things (like `res.send(200, res.body)`) but I'm not receiving anything. The only thing that seems to work is overriding `render` instead.

If there's a new preferred way to allow data to be passed along, can the documentation be updated? 

Edit: This update killed it: https://github.com/webpro/dyson/commit/03d4829d39a728844e2a31cab92471db4ad1b1a8

calling `return res.end();` on line 19 of `lib/response.js` basically keeps any default behavior from running past that point. Was there a reason for this? Is it a typo?

**Comment by webpro** [comment]
Thanks for the report, @phobetron. Could you please test your use case(s) if that line would be `return next()`? I'd be happy to release that as a patch.
