### ISSUE TITLE
Can't use OPTIONS method

### ISSUE THREAD

**Issue by taraujoz** [webpro/dyson#71]
Hi, I am trying to mock an OPTIONS call, however the fake server does not register it during initialization. I tried:

```
module.exports = {
    'path': '/user',
    'method': 'OPTIONS',
    'proxy': false,
    'cache': false,
    'template': userOptions
};
```

However, if I change to GET or any other method it works. So, how can I register a handler for an endpoint OPTIONS?

Thanks in advance!

**Comment by webpro** [comment]
@taraujoz, you should be having an `OPTIONS` preflight endpoint at the same path automatically, when you register any endpoint (like a `GET /user`). That doesn't work for you, or is it not what you need?

**Comment by webpro** [comment]
Closing this (also see [v0.11.0](https://github.com/webpro/dyson/releases/tag/0.11.0)).

**Comment by taraujoz** [comment]
I'm sorry for the delay in the response. I don't think I understood your answer, but maybe it's the clue. I need to generate the OPTIONS description for a GET endpoint, therefore I created this OPTIONS endpoint. So you are saying that an OPTIONS endpoint is automatically created when a GET endpoint is create, but how I modify its response?

**Comment by webpro** [comment]
Yes, the `OPTIONS` endpoint is automatically generated. Usually it's not necessary to modify the response headers:

```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:[origin]
```

What do you need to modify, or what is your issue exactly?

**Comment by taraujoz** [comment]
I need to write my own OPTIONS response, in order to make it similar to the ones in the Django REST framework (the objective is to mock a service based on django REST for testing). Is it possible?
