### ISSUE TITLE
is there an option to check request headers (without express)?

### ISSUE THREAD

**Issue by shanthakumarf22** [webpro/dyson#73]

**Comment by m3fawner** [comment]
Yes, you are able to get the request headers in the `template` callback function. It's the 5th parameter in the function signature.

```js
function(pathParams, queryParams, postBody, cookies, requestHeaders)
```

**Comment by m3fawner** [comment]
@webpro This can be closed

**Comment by webpro** [comment]
Indeed. Thanks @m3fawner!

**Comment by 5hanth** [comment]
Ok. Thanks.
