### ISSUE TITLE
Can I do a post request to a url and update a variable stored on the fake server?

### ISSUE THREAD

**Issue by sensorhound-nan** [webpro/dyson#74]
I want to update the output I get from a  "GET" request. so I do a "POST" request before it.
The code I set up the fake server is like this:
`
var data;

var generateResponse = function(req, res, next) {
	data += req.body;
    res.body = req.body;
    next();
};

module.exports = {
    path: '/dummy',
    type: 'POST',
    callback: generateResponse
};
`

`
var data;

module.exports = {
	path: "/dummy",
        type: "GET",
	template: data
}
`
But the result of the "GET" request is the same before and after the "POST" request.

I have also tried the set up the fake server's "GET" part like this:
`
module.exports = {
	path: "/dummy",
	template: data
}
`
Then I will have the error:
"ReferenceError: data is not defined"

So is there some suggestion to solve this problem. I am thinking of setting up a global variable shared by those two files and update the variable when I do a "POST" request. But I don't know how to do that. Someone help me please!

**Comment by webpro** [comment]
Hi @sensorhound-nan.

If you put that code in a single module, the variable `data` is shared within the same scope and it should work. (It's probably also a good idea to dynamically retrieve the `data` in the `GET` template, ie. `template: function() { return data; }`.)

Note that this is not how dyson is supposed to work. The short version is that I think state shouldn't be stored within a stub server. We can discuss it if you want to.

Btw, you can use three backticks (```) to surround code blocks.

**Comment by gkohen** [comment]
@webpro: To your last comment. Think of a scenario where a UI wants to show a list or orders: 
GET `/api/orders`
then add an order:
`POST `api/order`
body:
```
{
 customer: 'cookie monster'
 product: `broccoli`
 quantity: 1
}
```
Then the UI will issue the call again:
GET `/api/orders`
This last time the list will include the new order.
How can't it do that? By having scenarios in which an HTTP call will trigger entering a scenario. Then in your configuration you can say: "Answer this response if the scenario/status of the server is X"
You can of course reset the scenario to "default"
It's similar to what a mock server such as wiremock does:
http://wiremock.org/docs/stateful-behaviour/

**Comment by webpro** [comment]
@gkohen Dyson is not an actual (storage) server, it's a basic stub server. Still, you can choose to store data as we discussed, or use another solution :-)

**Comment by sensorhound-nan** [comment]
@webpro Actually, I just solve it using file system to create some files and modify them when doing a post request and get the information from the file when doing a get request. Thanks a lot!
