### ISSUE TITLE
Cannot disable cache

### ISSUE THREAD

**Issue by dz902** [webpro/dyson#78]
The default option for cache was supposed to be false, but in console it still shows `(cached)`, so I added "dyson.json" to API directory to manually set `cache: false`, but no luck, still seeing `(cached)`.

Any idea about this? Thanks.

Also want to know whether disabling cache means the API file is reloaded every time a request comes in, so I can edit it on the fly without the need to restart dyson.

**Comment by webpro** [comment]
* It is indeed `false` by default. Except for `GET` endpoints, so this should be documented properly.
* Caching is configured per endpoint, so you should set `cache: false` for the specific endpoint(s).
* The configuration is not reloaded automatically. Unfortunately, there's no option to reload dyson or endpoint(s) automatically on each change.

**Comment by dz902** [comment]
Thanks for the tips!

We have a project where development is primarily driven by UI, i.e. UI guys would mock API needed then backend guys would deduce data model from the mock.

As UI is quite volatile, we are expecting a lot of trial and errors. A watcher-like mechanism to auto-reload the points / files would be very helpful.

Any plan to add this in the future?

**Comment by webpro** [comment]
I agree some kind of auto-reloader should be in. Until then, you can also use something like [nodemon](https://github.com/remy/nodemon) to watch your files and restart dyson on changes.

**Comment by dz902** [comment]
Looking forward to it. Thanks.
