### ISSUE TITLE
Dummy image service is not registered automatically

### ISSUE THREAD

**Issue by dz902** [webpro/dyson#79]
In the README it says a dummy image service will be registered, but it was not. After installing `dyson-image`, it was still not registered, and I could not find how to register this service.

Please advise. Thanks!

**Comment by webpro** [comment]
Please refer to https://github.com/webpro/dyson/blob/master/dummy/get/image.js for an example.

**Comment by webpro** [comment]
See https://github.com/webpro/dyson-image for more details.

**Comment by webpro** [comment]
You can also install https://github.com/webpro/dyson-generators to do this:

```
var g = require('dyson-generators');
module.exports = {
  path: '/foo',
  template: {
    img: g.image.base64({width:200, height: 200});
  }
};
```

And then there's https://github.com/webpro/dyson-demo.

**Comment by dz902** [comment]
Thanks, just found out the first link.
