### ISSUE TITLE
Collection items is not unique

### ISSUE THREAD

**Issue by Grawl** [webpro/dyson#80]
I trying to create a collection, and items data is not unique.

Here is a quick example on how to reproduce this:

`/services/get/collection.js`

```js
module.exports = {
	path: '/collection',
	collection: true,
	cache: false,
	template: {
		random: Math.random(),
	}
}
```

`package.json`

```json
{
  "private": true,
  "scripts": {
    "services": "dyson services"
  },
  "devDependencies": {
    "dyson": "^1.0.2",
  }
}
```

Run `services`:

```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run services

> project@0.0.0 services /path/to/project
> dyson services

Registering GET service at /collection
Dyson listening at port: 3000
Resolving response for GET /collection
```

And got this:

```
[{"random":0.8456052458929002},{"random":0.8456052458929002},{"random":0.8456052458929002},{"random":0.8456052458929002},{"random":0.8456052458929002},{"random":0.8456052458929002},{"random":0.8456052458929002}]
```

Items is not unique as you can see. All the same.

Something is missing in my code?

**Comment by webpro** [comment]
You should make it dynamic, a function (it's evaluated only once now and set as the value).

**Comment by Grawl** [comment]
@webpro thank you, now it's unique:

```js
	template: {
		random: ()=> Math.random(),
	}
```

```json
[{"random":0.44458511570855785},{"random":0.9926197994943111}]
```

But can I make all the template to be unique? Like this:

```js
	template: () => {
		return {
			random: Math.random(),
		}
	}
```

I tried to do this, but it not makes items values unique.

**Comment by webpro** [comment]
Are you saying that with the second example, you get the same value for `random` each time?

**Comment by Grawl** [comment]
Yes.

**Comment by webpro** [comment]
But it's a fixed value, not a function anymore, as I've explained above. It evaluates the template, and if `collection === true` it puts this in an array x times. Going to close this for now, feel free to discuss further.

**Comment by Grawl** [comment]
Okay I got it. For me, it was unexpected that `g.id` from [`get/users.js` from dyson-demo](https://github.com/webpro/dyson-demo/blob/master/services/get/users.js) return unique value for each collection item, but not `Math.random()`

**Comment by webpro** [comment]
The difference between `g.id` and `Math.random()` is that the former is a *reference* to a function (which dyson will execute), and the latter is a function *call* which will pre-populate the property with the return value.
