### ISSUE TITLE
dyson is really good

### ISSUE THREAD

**Issue by danday74** [webpro/dyson#84]
Sorry to raise an issue for this but just wanted to say dyson is really good.

Many thanks for all your hard work on this project. Certainly deserves a lot more recognition in the community.

**Comment by webpro** [comment]
Well, this might be the best "issue" I've had here. Thank you for the shout out, it is much appreciated and very motivating!

Guess I'm pretty bad at marketing ;-) The [json-server](https://github.com/typicode/json-server) team did a better at job at this. But dyson is different and serves different people/use-cases, so I'm just happy people have more options now.

**Comment by danday74** [comment]
You are right json-server is a good project but doesn't fit my needs on my current project - dyson is well designed to just drop in a response and go with very little effort and next to no coding and its very transparent to co-developers exactly what is going on. You can drop endpoints and pick up new ones just by pointing to a diff folder. Great stuff, great design, thanks again!

**Comment by webpro** [comment]
Great review, thanks again!
