### ISSUE TITLE
dyson dependencies fail npm security audit

### ISSUE THREAD

**Issue by bsmithb2** [webpro/dyson#90]
Hi,

dyson 2.0.0 has a fixed dependency on serve-favicon 2.4.3, which has a dependency on fresh 0.5.0. 

Fresh versions prior to 0.52.0 have a audit vulnerability as discoverable with npm audit - https://nodesecurity.io/advisories/526

Is it possible to migrate to a version of serve-favicon greater or equal to 2.4.5? This will resolve the vulnerability. 

Thanks!

**Comment by webpro** [comment]
Updated dependencies in [v2.0.1](https://github.com/webpro/dyson/releases/tag/2.0.1)

**Comment by lorilew** [comment]
Does the version need updating so it can be released to npm?

**Comment by webpro** [comment]
No worries @lorilew, I use [release-it](https://github.com/release-it/release-it) for this :)
