### ISSUE TITLE
Documentation on what params are returned 

### ISSUE THREAD

**Issue by betovelandia** [webpro/dyson#94]
Hi, looking in to the docs I don't see any explanation of what is returned on `params` when creating a template, could we add documentation for that? I can do it if I get some pointers on where to find this information, thanks!

**Comment by webpro** [comment]
Please refer to https://github.com/webpro/dyson/blob/master/README.md#endpoint-configuration

Code is here: https://github.com/webpro/dyson/blob/master/lib/response.js#L15 (search for `templateArgs`)

Let me know if you're still missing something.

**Comment by betovelandia** [comment]
Yes, I don't see what is inside the params object, I need to know if I can get access to the URL of the page making the request, I suppose we are passing this to the Express server somewhere?

**Comment by betovelandia** [comment]
I guess I could rephrase my question, is there a way to access the referrer inside a template?

**Comment by webpro** [comment]
Sorry, undocumented feature. I think this is what you're after: set `exposeRequest: true` and you get the whole `req` object. Like in this test:

https://github.com/webpro/dyson/blob/8bf627309de912fd2c11025377a1307d7c9d620d/test/response.js#L83-L106

**Comment by betovelandia** [comment]
where would this `req` object be for a template?

```javascript
template: (params, query, body) => { 
 // How to access the req based on the parameters of the function?
```

I can add documentation for this feature, it sounds helpful.

**Comment by webpro** [comment]
It would be the first and only one (as it contains all the default ones): `template: req => {}`

**Comment by betovelandia** [comment]
So you would access it like this?

```javascript
template: req => { 
  // How to access the referrer
  const { referrer } = req;
}
```

**Comment by webpro** [comment]
It's the [`Express request`](https://expressjs.com/en/4x/api.html#req) object. This has all the request information, including headers.

By the way, the `referrer` should be in a header, which is available by default (without `exposeRequest`):

```
template: (params, query, body, cookies, headers) {}
```

**Comment by betovelandia** [comment]
Thanks!
