### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by symeonmattes** [webpro/dyson#97]
Hi,

Very good mock server. I have an issue (not so big) when I run dyson to a different port i.e. dyson myfile 8080. It prints out every 1-2sec 404 NOT FOUND: /. The service works as expected but it just prints out the message I mentioned.

Do you have any idea of what this might be?

Thanks

**Comment by webpro** [comment]
Maybe something else on your system is requesting localhost:8080? Request is coming from somewhere, dyson only responds :)

**Comment by symeonmattes** [comment]
Ic...It's a little bit complex the setup of the domain so this might be the case. Thanks for the info!
