### ISSUE TITLE
Dyson dependencies fail npm security audit - lodash needs updating

### ISSUE THREAD

**Issue by lorilew** [webpro/dyson#99]
Hi 

Would it be possible to update the version of Lodash that Dyson uses?

=== npm audit security report ===                        
                                                                                
│ High                  │ Prototype Pollution                      
│ Package           │ lodash
│ Patched in        │ >=4.17.12 
│ Dependency of │ dyson    
│ Path                  │ dyson > lodash   
│ More info          │ https://npmjs.com/advisories/1065

Thanks

**Comment by webpro** [comment]
Sure, could you please open a PR for this?

**Comment by lorilew** [comment]
https://github.com/webpro/dyson/pull/100

**Comment by sobmortin** [comment]
I am also having issues with this. Thank you for the Pull Request.

**Comment by webpro** [comment]
Just released [v2.0.5](https://github.com/webpro/dyson/releases/tag/2.0.5)
